
#  ==================== Monitors  ====================

# monitor = MonitorName     Resolution@refeshrRate,      position,      scale
# monitor = DP-1,           preferred,                   0x0,           1      ,vrr, 2
# monitor = DP-2,           preferred,                   1920x0,        1

# Notes:
# You can find your monitor name usign 'hyprctl monitors' command


# This sets workspaces to monitor
# workspace = WorkspaceNumber,      monitor:MonitorName
# workspace = 1,                    monitor:DP-1
# workspace = 2,                    monitor:DP-1
# workspace = 3,                    monitor:DP-1
# workspace = 4,                    monitor:DP-1

#  ===================================================
