# ░█░█░█░█░█▀█░█▀▄░░░█░█░█▀█░█▀▄░▀█▀░█▀█░█▀▄░█░░░█▀▀░█▀▀
# ░█▀█░░█░░█▀▀░█▀▄░░░▀▄▀░█▀█░█▀▄░░█░░█▀█░█▀▄░█░░░█▀▀░▀▀█
# ░▀░▀░░▀░░▀░░░▀░▀░░░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀░░▀▀▀░▀▀▀░▀▀▀

$mainMod            = SUPER

$terminal           = foot
$editor             = foot -e --override=colors.alpha=1 nvim
$fileManager        = foot -e yazi
$musicPlayer        = foot -e rmpc
$menu               = walker 
$rmenu              = ~/Dotfiles/bin/launchrofi -r
$clipboard          = walker -s clippy -p "󰅇 Clipboard" 
$browser            = bash ~/Dotfiles/scripts/open-browser 
$loginManager       = hyprlock
$screenshot         = ~/Dotfiles/bin/launchrofi --screenshot_menu

