# foot.ini - Configuration for foot terminal

# Font settings
font = CaskaydiaMono Nerd Font:size=14

gamma-correct-blending=no

[colors-dark]

foreground = CACACA
background = 212326


alpha = 1

[tweak]
surface-bit-depth = 8-bit
