# Riftbar Configuration
[general]
enable_ipc = true

[bars.main]
modules_left = ["hyprland/workspaces"]
modules_center = ["custom/mako", "clock"]
modules_right = ["box/right"]

[bars.osd]
modules_center = ["box/osd"]
layer = "overlay"
reserve_space = false
open_on_launch = false
margin_top = 15
margin_left = 820
margin_right = 820

# Clock module configuration
[clock]
format = "%b %d  %H:%M"
interval = 5000  # milliseconds
tooltip = true
tooltip_format = "%d %B %Y"
on_click = "ewwii open calendar --toggle --no-daemonize & ewwii close on_clickcenter musiccenter"  # Optional: command to run on click

# Available format placeholders (uses date command format):
# %H _ Hour (00_23)
# %M _ Minute (00_59)
# %S _ Second (00_59)
# %A _ Full weekday name
# %a _ Abbreviated weekday name
# %B _ Full month name
# %b _ Abbreviated month name
# %d _ Day of month (01_31)
# %Y _ Year with century

[workspaces]
min_workspace_count=2

# Network module configuration
[network]
on_click = "bash ~/Dotfiles/scripts/quickcenter.sh &  ewwii close calendar"
format = "{icon}"
format_disconnected = "󰌙"
format_ethernet = " "
interval = 5
tooltip = true

# Audio module configuration
[audio]
format = "{icon}"
interval = 150  # milliseconds
tooltip = true
on_click = "bash ~/Dotfiles/scripts/quickcenter.sh &  ewwii close calendar" # Default: toggle mute
on_click_right = "nohup foot --override=colors.alpha=1 --app-id=binarydotsTUI -e wiremix >/dev/null 2>&1 &"
on_scroll_up = ""  # Default: increase volume by scroll_step
on_scroll_down = ""  # Default: decrease volume by scroll_step
scroll_step = 5  # Volume change step (percentage)

# Battery configuration
[battery]
format = "{icon}"
charging_icon = "󰂄"
on_click = "bash ~/Dotfiles/scripts/quickcenter.sh &  ewwii close calendar"
interval = 30
tooltip = true

[tray]
icon_size = 20
spacing = 2

[boxes.osd]
modules = ["audio", "sliders/osd"]
spacing = 10

[boxes.right]
modules = ["revealer/tray","box/quicksettings"]

# Box widgets _ simple containers
[boxes.quicksettings]
modules = ["network", "audio", "battery"]
on_click = "bash ~/Dotfiles/scripts/quickcenter.sh &  ewwii close calendar"
spacing = 5
orientation = "horizontal"  # horizontal or vertical (default: horizontal)

# Revealer widgets _ containers that reveal on hover or click
[revealers.tray]
modules = ["tray"]
spacing = 10
trigger = " "  # Text/icon for the trigger button
transition = "slide_left"  # slide_left, slide_right, slide_up, slide_down, crossfade
transition_duration = 600  # milliseconds
reveal_on_hover = false  # Reveal on hover instead of click
# orientation = "horizontal"  # horizontal or vertical (default: horizontal)

# Custom modules
[custom_modules.mako]
on_click = "bash ~/Dotfiles/config/mako/scripts/walker.sh"
on_click_right = "bash ~/Dotfiles/config/mako/scripts/riftbar.sh -d"
exec = "~/Dotfiles/config/mako/scripts/riftbar.sh"
interval = 1
format = "{}"

[sliders.osd]
listen = true
exec = "bash ~/Dotfiles/scripts/vol_osd.sh"
scroll_cmd = "pamixer --set-volume {}"
